# Generated by Django 3.0 on 2019-12-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='st',
            field=models.BinaryField(blank=True),
        ),
    ]
